# Generated by Django 4.1.7 on 2023-03-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_order_quantity_remove_order_product_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
    ]
