# Generated by Django 4.1.7 on 2023-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_order_address_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
