# Generated by Django 4.1.7 on 2023-03-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='msrp',
        ),
    ]
