# Generated by Django 4.1.7 on 2023-03-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_price_product_msrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='msrp',
            new_name='price',
        ),
    ]
