# Generated by Django 4.1.7 on 2023-03-30 08:03

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_rename_msrp_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='msrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=pages.models.Product.discount_price, max_digits=10),
        ),
    ]
