# Generated by Django 4.1.7 on 2023-03-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_product_msrp_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='msrp',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
