# Generated by Django 4.1.7 on 2023-03-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_product_msrp_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='msrp',
        ),
    ]
