# Generated by Django 4.1.7 on 2023-03-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
