# Generated by Django 4.1.7 on 2023-03-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='msrp',
            new_name='price',
        ),
    ]
