# Generated by Django 4.1.7 on 2023-05-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_carrier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_days_estimate',
            field=models.IntegerField(null=True),
        ),
    ]
