# Generated by Django 4.1.7 on 2023-03-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customer_postal_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='postal_address',
        ),
    ]
