# Generated by Django 4.1.7 on 2023-03-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customeraddress_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
